### ISSUE TITLE
Can an evolved push program (or function) be converted to a "normal" Python function?

### ISSUE THREAD

**Issue by nbro** [erp12/pyshgp#155]
Once the evolutionary process has terminated, for instance, after you have called the `run` method of a `GeneticAlgorithm` object, you get an instance of the `Individual` class, which supposedly represents the best individual across all generations. This individual has several fields, including the `genome` and the `program`, which is a property that returns an object of type `CodeBlock`, which can be run with the Push interpreter. 

However, what if we need to evolve functions that ultimately should be run as "normal" Python functions? Do we always need a Push interpreter to run this `CodeBlock` inside the individual? Is there a way to convert the `CodeBlock` to a normal Python function, in a similar way that `deap` converts the tree expression to a Python function with the [`compile`](https://github.com/DEAP/deap/blob/master/deap/gp.py#L460) method?

After having looked at the source code of `compile`, it seems that it just calls Python's built-in function `eval` with the tree expression represented by [a string that represents a sequence of nested calls to functions](https://github.com/DEAP/deap/blob/master/deap/gp.py#L88), for example, `"if_food_ahead(move_forward, move_forward)"`, where `if_food_ahead` and `move_forward` are two Python functions.  It should be possible to do the same thing in PyshGP, provided that we can convert the prefix (or postfix) notation/representation (which I think is what is being used in PyshGP)  of a program/code block to the normal infix notation and provide a map between names (identifiers) to the actual Python function (as the second argument to `eval`). The problem is that I am not sure if a Push program can easily be converted to a tree-based representation. Maybe the issue https://github.com/erp12/pyshgp/issues/138 may be useful (to answer that question).

The first problem that I see to achieve this, as far as I understand, is that Push programs may not be valid programs, i.e. they may contain some instructions that do not have the correct number or type of inputs. However, this can probably be overcome by parsing the program and removing the instructions that are not valid. In any case, they are ignored by the interpreter.

**Comment by erp12** [comment]
This is a very interesting topic. In my mind, there are 2 different interpretations of using Push programs as a Python functions.

1. Putting a push program into an object that can be called like a python function.
2. Converting a push program into Python source code, or a Python AST.

You mentioned using `eval`, which implies option 2, so let's start there. You correctly point out that the syntax of a Push program isn't a standard tree-like structure, therefore we would need some kind of translation process to get the Push code into a Python AST.  This is a big challenge because of Push's execution model. [Push uses a stack-based execution](http://faculty.hampshire.edu/lspector/pubs/push3-gecco2005.pdf) to ensure that every program is "safe" to run. Every time Push program is run with different input values, the state of the stacks is different and therefore different instruction may or may not be executed/skipped.  It is hard to imagine what kind of process would translate a Push code into equivalent Python code for all inputs.

If getting source code as an output is a requirement for your use cases, I would recommend looking into grammatical evolution (GE) or grammar guided genetic programming (G3P). The python library [PonyGE](https://github.com/PonyGE/PonyGE2) might be a good place to start. You may have also seen that we recently proposed a new GP method that is a cousin of PushGP except it produced source code. It is called [Code Building Genetic Programming](https://arxiv.org/pdf/2008.03649.pdf). Unfortunately, the "production-ready" implementations are still a work in progress. 

Now for option 1: converting the Push code into a callable Python object. This is definitely feasible.  If you know what `PushInterpeter` you want to run your Push code with, you can bind the two together into a callable object. Something like this:

```python
push_interpreter = PushInterpreter(...)  # configure this however you want (custom instructions, etc.)

class FunctionFromPush:

  def __init__(self, code: CodeBlock):
    self.code = code

  def __call__(self, *args):
    # If you have a specific method signature, you could also use that.
    push_interpreter.run(self.code, inputs)

# Create the python "function"
f = FunctionFromPush(push_code_here)

# Call the function
f("Hello world", 5) 
```

This approach is a little brittle with respect to the `PushInterpreter`. If the interpreter changes it might change the behavior of the Push program. Also, I am not sure if the "function" we created would be serializable, which might limit portability.

_______________

In general, this is an open research area. If you have any ideas, I would encourage you to dig in and try them out! Hopefully the PyshGP codebase can be a good starting point and feel free to continue the discussion here. If you end up trying something like what DEAP does, I would love to hear how it turns out.

**Comment by erp12** [comment]
Seems like there is currently no more discussion about this topic.

At the time of writing, it is out-of-scope for PyshGP (or any known PushGP system in the field) to synthesize valid code in the host language (in this case Python).
