### ISSUE TITLE
Keyboard interrupt ^C does not halt processing

### ISSUE THREAD

**Issue by Vaguery** [erp12/pyshgp#53]
I was running one of the examples on my laptop, and got _super boooooored_, but `ctrl-C` just raises some kind of caught exception and leaves a pile of Python processes running.

Are you by any chance catching _all_ exceptions, including `KeyboardInterrupt`? Because that's not really the way I would like `ctrl-C` to work, as it turns out. 😃

**Comment by Vaguery** [comment]
BTW, I had to eventually `kill -9` the root `Python` process.

**Comment by erp12** [comment]
No this is a consequence of the multiprocessing library that is being used. Likely you hit `ctrl-C` while multiple processes were working. My understanding of the behavior you are seeing is that the master process stays open until every other process finishes its task so that it can close them and not leave zombie workers.

If you see this behavior using `-max_workers 1`, then I might be wrong, but I can assure you that I am not catching all exceptions anywhere. (With the exception of a one time gathering command line args which only happens once, and is not expected to stick around as mentioned in #54 and #46 )

**Comment by Vaguery** [comment]
Maybe you _could_ catch `KeyboardInterrupt` then, and use it to gracefully shut down the workers?

**Comment by erp12** [comment]
That seems reasonable. I will look into that.

**Comment by erp12** [comment]
This issue was related to multiprocessing, which has been removed from pyshgp. Closing this issue.
