### ISSUE TITLE
Dumping and loading models

### ISSUE THREAD

**Issue by shurain** [erp12/pyshgp#96]
Is there a way to dump a model and load it later for prediction? Specifically, how do I use the final program printed out at the end of the GP run to perform a prediction task at later times?

**Comment by erp12** [comment]
Programs/models have been technically JSON serializable for a few versions now, but it was hacky and bad. For example, the Push code of the program could be read from JSON but you wouldn't know what Push interpreter settings the program was produced with, and thus you couldn't be sure  you would get the same behavior out of the program.

Recently #127 added a program abstraction that is serializable to binary (assuming all instructions are serializable. No lambdas!). It should be a better solution to this problem.

```python
est = PushEstimator(... )
est.fit(X, y)
program = est.get_program()
program.save("dir/file.model")
# ... later
new_est = PushEstimator(... )
new_est.load("dir/file.model")
new_est.predict(X2)
```

This feature is only lightly tested and documented, but I am going to close this issue because the core problem is solved.
